### ISSUE TITLE
Latent Diffusion Model? Code?

### ISSUE THREAD

**Issue by Liruieat** [hvcl/ConNucDA#1]
Thank you for your outstanding work on this project. I am very interested in the methodology used in your paper, specifically whether it is based on Semantic Diffusion Models (DM) or Latent Diffusion Models (LDM). Additionally, I would like to know if you could upload the code for your implementation, as it would greatly assist in my understanding and application of your work.

**Comment by hjoh01** [comment]
Hi, thank you for your interest in our work!
I am currently working on releasing the code utilized for this project. At the moment, only the image generation part (LDM) has been uploaded, but I will soon update it to include scripts and a README file that explains how to use them.
Please stay tuned for more detailed information and the complete code. 
Thank you once again for your interest!

**Comment by windygoo** [comment]
look forward

**Comment by windygoo** [comment]
any update?

**Comment by hjoh01** [comment]
@Liruieat @windygoo 
Thank you for waiting. Label synthesis code is available now!

**Comment by windygoo** [comment]
> @Liruieat @windygoo Thank you for waiting. Label synthesis code is available now!

Thank you for sharing the code! Really appreciate your work and contribution to the community. The label synthesis implementation will be very helpful for understanding and reproducing the work.
